description: dacheng-math

environment:
  image: amlt-sing/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04
  setup:
    - export PATH=$$PATH:/home/aiscuser/.local/bin
    - pip install packaging
    - pip install ninja
    - pip install https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.0.post2/flash_attn-2.8.0.post2+cu12torch2.5cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
    - pip install vllm
    - pip install onnxruntime-gpu
    - pip install datasets
    - pip install transformers
    - pip install python-dotenv
    - pip install uuid
    - pip install openai
    - pip install math-verify
    - pip install jsonlines
    - pip install tqdm
    - pip install pandas
    - pip install wandb

code:
  local_dir: /Users/wendacheng/Projects/TruthRL

target:
  service: sing
  name: Feeds
  workspace_name: CS-NewsAndFeeds-Singularity

storage:
  external:
    storage_account_name: csnewsandfeeds4150361735
    container_name: unium
    mount_dir: /mnt/blob_output

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
- name: dc-math-grpo-bsz
  sku: G8-A100
  sla_tier: Standard
  command:
    - cd src
    - pip install -e . --user
    - pip install deepspeed -U
    - cd ..
    - bash ./src/scripts/grpo.sh
  submit_args:
    env:
      {
        BLOB_OUTPUT_PATH: /mnt/blob_output/v-dachengwen/,
        AMLT_DOCKERFILE_TEMPLATE: DEFAULT,
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/b6dc87f3-c479-49c8-8cb5-7896da3ff895/resourceGroups/AMLStudio/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rankfun_aml,
        CUDA_LAUNCH_BLOCKING: 1,
        MKL_SERVICE_FORCE_INTEL: 1,
        HF_TOKEN: $HF_TOKEN,
        WANDB_API_KEY: $WANDB_API_KEY,
      }